module.exports= {
    ADD_TO_CART : "ADD_TO_CART", 
    ADD_QAUNTITY : "ADD_QAUNTITY", 
    MINES_QAUNTITY : "MINES_QAUNTITY", 
    REMOVE_ITEM : "REMOVE_ITEM", 
    ORDER_ITEM : "ORDER_ITEM",
    REMOVE_FROM_CART: "REMOVE_FROM_CART"
}